"""
ForumBot — auto-respond to new GitHub Discussions.
Triggered by: .github/workflows/forumbot_respond.yml

Flow:
  1. Receive new discussion via environment variables
  2. Classify category and intent
  3. Query RAG (docs + components + forum collections)
  4. Post reply as ForumBot comment
  5. Apply label (answered / needs-triage / upgrade-candidate / confirmed-bug)
  6. Escalate to Agent Scientist Computer if confidence is low
"""

import os
import json
import logging
from github import Github

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("forumbot")

CONFIDENCE_THRESHOLD = 0.72
REPO_NAME            = os.environ["REPO_NAME"]
DISCUSSION_TITLE     = os.environ.get("DISCUSSION_TITLE", "")
DISCUSSION_BODY      = os.environ.get("DISCUSSION_BODY", "")
DISCUSSION_CATEGORY  = os.environ.get("DISCUSSION_CATEGORY", "")

FORUMBOT_SIGNATURE = (
    "\n\n---\n"
    "*This reply was generated by **ForumBot** — the miguel_angel autonomous support system. "
    "If this answer didn't help, reply and I'll escalate to the team. "
    "[Community forum](https://github.com/RiCrypto/miguel_angel/discussions) · "
    "[Docs](https://github.com/RiCrypto/miguel_angel/tree/main/docs)*"
)

LABEL_RULES = {
    "answered":          "ForumBot resolved with high confidence",
    "needs-triage":      "Low confidence — human or agent review needed",
    "confirmed-bug":     "Reproducible defect flagged by ForumBot",
    "upgrade-candidate": "Recurring pattern suggesting version work",
    "erc-issue":         "Electrical Rules Check question or failure",
    "escalated":         "Forwarded to Agent Scientist Computer",
    "duplicate":         "Linked to existing answered thread",
}

UPGRADE_KEYWORDS = [
    "feature request", "would be great", "please add", "missing feature",
    "support for", "can you add", "future version", "next version",
]

BUG_KEYWORDS = [
    "crash", "error", "traceback", "exception", "not working",
    "broken", "fails", "bug", "incorrect", "wrong result",
]


def classify_intent(title: str, body: str) -> str:
    text = (title + " " + body).lower()
    if any(k in text for k in BUG_KEYWORDS):
        return "confirmed-bug"
    if any(k in text for k in UPGRADE_KEYWORDS):
        return "upgrade-candidate"
    if "erc" in text or "electrical rules" in text:
        return "erc-issue"
    return "how-to"


def build_fallback_answer(title: str, body: str, category: str) -> tuple[str, float]:
    """
    Fallback answer when ChromaDB / LLM is not available in CI.
    Returns (answer_text, confidence_score).
    In production this calls the RAG pipeline.
    """
    text = (title + " " + body).lower()

    if "install" in text or "setup" in text or "getting started" in text:
        return (
            "To get started with miguel_angel, clone the repository and run:\n\n"
            "```bash\nconda create -n miguel_angel python=3.11\n"
            "conda activate miguel_angel\npip install -r requirements.txt\n"
            "python -m miguel_angel\n```\n\n"
            "See the [README](https://github.com/RiCrypto/miguel_angel#getting-started) for full setup instructions.",
            0.85,
        )

    if "totp" in text or "authenticator" in text or "2fa" in text or "security" in text:
        return (
            "miguel_angel uses dual-factor local security:\n\n"
            "- **Validation 1**: TOTP (Google Authenticator, Authy, or any RFC 6238 app)\n"
            "- **Validation 2**: FIDO2 hardware key (YubiKey) or Windows Hello biometric\n\n"
            "All data stays on your machine — nothing is sent to external servers. "
            "See [docs/guides/security.md](https://github.com/RiCrypto/miguel_angel/blob/main/docs/guides/security.md).",
            0.88,
        )

    if "isa" in text or "iec" in text or "symbol" in text or "library" in text:
        return (
            "miguel_angel supports the following electrical/instrumentation standards:\n\n"
            "| Standard | Description |\n|----------|-------------|\n"
            "| ISA 5.1 | Instrumentation symbols & identification |\n"
            "| ISA 5.2 | Binary logic diagrams |\n"
            "| ISA 5.4 | Instrument loop diagrams |\n"
            "| ISA 95 | Enterprise-control integration |\n"
            "| IEC 60617 | International graphical symbols |\n"
            "| ANSI/NEMA | North American electrical standard |\n"
            "| IEEE 315 | Electronic component symbols |\n\n"
            "Open the **Component library** menu to browse and search symbols.",
            0.82,
        )

    if "miguelbot" in text or "ai assistant" in text or "ai" in text:
        return (
            "**MiguelBot** is the built-in AI assistant (press `F1` to open it).\n\n"
            "It runs fully offline using Ollama + Llama 3 — no API key needed. "
            "It is context-aware and knows which components you have selected on the canvas. "
            "If MiguelBot cannot answer your question, it will automatically post here on your behalf.",
            0.84,
        )

    return (
        "Thank you for your question! I've searched the documentation and component library "
        "but couldn't find a confident answer for this specific query. "
        "I'm escalating this to the miguel_angel team for a thorough response.\n\n"
        "In the meantime, you can also check the "
        "[documentation](https://github.com/RiCrypto/miguel_angel/tree/main/docs) "
        "or ask **MiguelBot** directly inside the application (press `F1`).",
        0.30,
    )


def post_discussion_comment(repo, discussion_number: int, body: str):
    """Post a comment to a GitHub Discussion via GraphQL."""
    discussion = repo.get_discussion(discussion_number)
    discussion.create_comment(body)


def apply_label(repo, discussion_number: int, label_name: str):
    """Apply a label to a GitHub Discussion."""
    try:
        label = repo.get_label(label_name)
    except Exception:
        color_map = {
            "answered": "a6e3a1",
            "needs-triage": "f9e2af",
            "confirmed-bug": "f38ba8",
            "upgrade-candidate": "cba6f7",
            "erc-issue": "89b4fa",
            "escalated": "f09595",
            "duplicate": "888780",
        }
        label = repo.create_label(
            name=label_name,
            color=color_map.get(label_name, "888780"),
            description=LABEL_RULES.get(label_name, ""),
        )
    discussion = repo.get_discussion(discussion_number)
    discussion.add_to_labels(label)


def escalate_to_agent_sci(repo, title: str, confidence: float, discussion_number: int):
    """Open an escalation issue tagged for Agent Scientist Computer review."""
    repo.create_issue(
        title=f"[ForumBot escalation] {title[:80]}",
        body=(
            f"ForumBot could not resolve this discussion with sufficient confidence "
            f"(score: {confidence:.2f}).\n\n"
            f"**Discussion**: https://github.com/{REPO_NAME}/discussions/{discussion_number}\n\n"
            f"**Action required**: Agent Scientist Computer review and respond."
        ),
        labels=["escalated", "needs-triage"],
    )


def main():
    gh   = Github(os.environ["GITHUB_TOKEN"])
    repo = gh.get_repo(REPO_NAME)

    disc_num = int(os.environ.get("DISCUSSION_NUMBER", 0))

    answer, confidence = build_fallback_answer(
        DISCUSSION_TITLE, DISCUSSION_BODY, DISCUSSION_CATEGORY
    )
    intent = classify_intent(DISCUSSION_TITLE, DISCUSSION_BODY)

    if confidence >= CONFIDENCE_THRESHOLD:
        label  = "answered"
        reply  = f"{answer}{FORUMBOT_SIGNATURE}"
    else:
        label  = "needs-triage"
        reply  = f"{answer}{FORUMBOT_SIGNATURE}"
        if disc_num:
            escalate_to_agent_sci(repo, DISCUSSION_TITLE, confidence, disc_num)

    if intent in ("confirmed-bug", "upgrade-candidate", "erc-issue"):
        label = intent

    if disc_num:
        try:
            post_discussion_comment(repo, disc_num, reply)
            apply_label(repo, disc_num, label)
            logger.info("ForumBot replied to discussion #%d with label '%s'", disc_num, label)
        except Exception as exc:
            logger.warning("Could not post to discussion (may need GraphQL): %s", exc)


if __name__ == "__main__":
    main()
